##### General settings
env: unset
oc_namespace: operator-pipeline-{{ env }}
service_account_name: operator-pipeline-admin
suffix: "{{ env }}"

operator_pipeline_private_key_local_path: ../../vaults/{{ env }}/operator-pipeline.key
operator_pipeline_private_cert_local_path: ../../vaults/{{ env }}/operator-pipeline.pem

operator_pipeline_quay_token: ../../vaults/common/dockerconfig.json
operator_pipeline_github_bot_token: ../../vaults/common/github-bot-token.txt
operator_pipeline_webhook_secret: ../../vaults/common/github-webhook-secret.txt