---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-ci-results
spec:
  params:
    - name: preflight_results_exists
    - name: md5sum
    - name: pyxis_url
    - name: cert_project_id
    - name: operator_version
  workspaces:
    - name: results
  steps:
    - name: get-ci-results
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.results.path)
      script: |
        #! /usr/bin/env bash
        # Curl Pyxis results endpoint
        # If results exists, store them in the workspace, if not- fail

        PREFLIGHT_RESULTS_EXISTS="$(params.preflight_results_exists)"
        echo $PREFLIGHT_RESULTS_EXISTS
        if [ "$PREFLIGHT_RESULTS_EXISTS" == "true" ]; then
          echo "Trying to retrieve the preflight results again.."
        fi
