---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-ci-results2
spec:
  params:
    - name: result_resp_code
    - name: md5sum
    - name: pyxis_url
    - name: cert_project_id
    - name: operator_version
  workspaces:
    - name: results
  steps:
    - name: get-ci-results
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.results.path)
      script: |
        #! /usr/bin/env bash
        # Curl Pyxis results endpoint
        # If results exists, store them in the workspace, if not- fail

        RESULT_RESP_CODE="$(params.result_resp_code)"
        if [ "$RESULT_RESP_CODE" == "404" ]; then
          echo "Trying to retrieve the preflight results again.."
        fi
