---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hash-submission-content
spec:
  params:
    - name: operator_name
    - name: operator_version
  results:
    - name: certification_hash
  workspaces:
    - name: source
  steps:
    - name: hash-submission-content
      image: registry.access.redhat.com/ubi8-minimal
      workingDir: $(workspaces.source.path)
      script: |
        #! /usr/bin/env bash
        # pushd operators/$(params.operator_name)/$(params.operator_version)
        # create md5sum of submission
        # find . -not -name "Dockerfile" -type f -printf '%f\t%p\n' | sort -V -k1 | cut -d$'\t' -f2 | tr '\n' '\0' | xargs -r0 -I {} md5sum "{}" > ../hashes.txt
        # cat ../hashes.txt | tee $(results.certification_hash.path)
        echo "4321" | tee $(results.certification_hash.path)
