---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: submission-validation
spec:
  params:
    - name: git_username
    - name: git_pr_title
    - name: pyxis_url
      default: https://catalog.redhat.com/api/containers
  results:
    - name: cert_project_id
    - name: operator_name
    - name: bundle_version
  workspaces:
    - name: source
  steps:
    - name: get-cert-project-id
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        # cat ci.yaml | yq e '.cert_project_id' - | tee $(results.cert_project_id.path)
        echo "1234abcd" | tee $(results.cert_project_id.path)

    - name: verify-user-submiting
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        # Python script
        echo "ok"

    - name: verify-pr
      workingDir: $(workspaces.source.path)
      # here we'll use custom image with Python script
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        # 1. verify via regex if PR title follows convention
        # 2. Verify that there is no other open PRs for this operator

        echo "test" | tee $(results.operator_name.path)
        echo "1.2.3" | tee $(results.bundle_version.path)
        echo "ok"
