---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-changed-directories
spec:
  params:
    - name: operator_name
    - name: bundle_version
    - name: pr_head_label
    - name: git_repo_url
    - name: base_branch
      default: main
  steps:
    - name: get-cert-project-id
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      script: |
        #! /usr/bin/env bash
        verify_changed_dirs \
          --operator_name="$(params.operator_name)" \
          --bundle-version="$(params.bundle_version)" \
          --pr_head_label="$(params.pr_head_label)" \
          --git_repo_url="$(params.git_repo_url)" \
          --base_branch="$(params.base_branch)"
