---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-changed-directories
spec:
  params:
    - name: operator_name
    - name: operator_version
    - name: pr_head_label
    - name: git_organisation
    - name: repository
    - name: base_branch
  steps:
    - name: get-cert-project-id
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      script: |
        #! /usr/bin/env bash
        verify_changed_dirs \
          --operator_name="$(params.operator_name)" \
          --operator-version="$(params.operator_version)" \
          --pr_head_label="$(params.pr_head_label)" \
          --organisation="$(params.git_organisation)" \
          --repository="$(params.repository)" \
          --base_branch="$(params.base_branch)"
