---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: operator-hosted-pipeline
spec:
  params:
    - name: git_pr_branch
    - name: git_pr_title
    - name: git_pr_url
    - name: git_repo_url
    - name: git_username
    - name: pyxis_url
    - name: bundle_path
    - name: preflight_min_version
    - name: ci_min_version
    - name: registry_url
      default: quay.io
  workspaces:
    - name: repository
    - name: results
  tasks:
    # Git clone
    - name: checkout
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git_repo_url)
        - name: revision
          value: $(params.git_pr_branch)
      workspaces:
        - name: output
          workspace: repository
          subPath: src

    # Validate submission
    - name: submission-validation
      runAfter:
        - checkout
      taskRef:
        name: submission-validation
      params:
        - name: git_username
          value: $(params.git_username)
        - name: git_pr_title
          value: $(params.git_pr_title)
        - name: pyxis_url
          value: $(params.pyxis_url)
      workspaces:
        - name: source
          workspace: repository
          subPath: src

    # reserve operator name
    - name: reserve-operator-name
      runAfter:
        - submission-validation
      taskRef:
        name: reserve-operator-name
      params:
        - name: operator_name
          value: "$(tasks.submission-validation.results.operator_name)"

    # additional checks
    - name: operator-validation
      runAfter:
        - reserve-operator-name
      taskRef:
        name: operator-validation
      params:
        - name: bundle_path
          value: "$(params.bundle_path)"
      workspaces:
        - name: source
          workspace: repository
          subPath: src

    - name: yaml-lint
      runAfter:
        - reserve-operator-name
      taskRef:
        name: yaml-lint
      params:
        - name: args
          value: ["-d {extends: default, rules: {line-length: {max: 180, level: warning}}}", "$(params.bundle_path)"]
      workspaces:
        - name: shared-workspace
          workspace: repository
          subPath: src

    - name: digest-pinning
      runAfter:
        - reserve-operator-name
      taskRef:
        name: digest-pinning
      params:
        - name: bundle_path
          value: "$(params.bundle_path)"
      workspaces:
        - name: source
          workspace: repository
          subPath: src

    - name: verify-pinned-digest
      runAfter:
        - digest-pinning
      taskRef:
        name: verify-pinned-digest
      params:
        - name: dirty_flag
          value: "$(tasks.digest-pinning.results.dirty_flag)"

    - name: content-hash
      runAfter:
        - reserve-operator-name
      taskRef:
        name: content-hash
      params:
        - name: bundle_path
          value: "$(params.bundle_path)"
      workspaces:
        - name: source
          workspace: repository
          subPath: src

    - name: verify-changed-directories
      runAfter:
        - reserve-operator-name
      taskRef:
        name: verify-changed-directories
      params:
        - name: operator_name
          value: "$(tasks.submission-validation.results.operator_name)"
        - name: operator_version
          value: "$(tasks.submission-validation.results.operator_version)"
        - name: git_pr_branch
          value: $(params.git_pr_branch)

    - name: query-publishing-checklist
      runAfter:
        - reserve-operator-name
      taskRef:
        name: query-publishing-checklist
      params:
        - name: cert_project_id
          value: "$(tasks.submission-validation.results.cert_project_id)"

    # Try to retrieve results
    - name: get-ci-results-attempt
      runAfter:
        - operator-validation
        - yaml-lint
        - verify-pinned-digest
        - content-hash
        - verify-changed-directories
        - query-publishing-checklist
      taskRef:
        name: get-ci-results-attempt
      params:
        - name: pyxis_url
          value: $(params.pyxis_url)
        - name: md5sum
          value: "$(tasks.content-hash.results.md5sum)"
        - name: cert_project_id
          value: "$(tasks.submission-validation.results.cert_project_id)"
        - name: operator_version
          value: "$(tasks.submission-validation.results.operator_version)"
      workspaces:
        - name: results
          workspace: results
          subPath: results

    # If we didn't got the CI pipeline preflight test results
    # - run preflight here
    # and try to retrieve them again
    - name: placeholder-run-ci-pipeline
      runAfter:
        - get-ci-results-attempt
      taskRef:
        name: placeholder-run-ci-pipeline
      params:
        - name: preflight_results_exists
          value: "$(tasks.get-ci-results-attempt.results.preflight_results_exists)"

    - name: get-ci-results
      runAfter:
        - placeholder-run-ci-pipeline
      taskRef:
        name: get-ci-results
      params:
        - name: preflight_results_exists
          value: "$(tasks.get-ci-results-attempt.results.preflight_results_exists)"
        - name: pyxis_url
          value: $(params.pyxis_url)
        - name: md5sum
          value: "$(tasks.content-hash.results.md5sum)"
        - name: cert_project_id
          value: "$(tasks.submission-validation.results.cert_project_id)"
        - name: operator_version
          value: "$(tasks.submission-validation.results.operator_version)"
      workspaces:
        - name: results
          workspace: results
          subPath: results

    # Verify the CI results
    - name: verify-ci-results
      runAfter:
        - get-ci-results
      taskRef:
        name: verify-ci-results
      params:
        - name: preflight_min_version
          value: $(params.preflight_min_version)
        - name: ci_min_version
          value: $(params.ci_min_version)
      workspaces:
        - name: results
          workspace: results
          subPath: results

    # Rebuild images.
    # Those steps are also a part of the CI pipeline.
    - name: dockerfile-creation
      runAfter:
        - verify-ci-results
      taskRef:
        name: dockerfile-creation
      params:
        - name: bundle_path
          value: "$(params.bundle_path)"
      workspaces:
        - name: source
          workspace: repository
          subPath: src

    - name: build-bundle
      runAfter:
        - dockerfile-creation
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: &bundleImage "$(params.registry_url)/$(context.pipelineRun.namespace)/$(tasks.operator-validation.results.package_name):$(tasks.operator-validation.results.bundle_version)"
        - name: CONTEXT
          value: "$(params.bundle_path)"
        # TODO TLS verification disabled for demo purposes
        - &buildahNoTlsVerify
          name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: repository
          subPath: src

    - name: generate-index
      runAfter:
        - build-bundle
      taskRef:
        name: generate-index
      params:
        - name: bundle_image
          value: *bundleImage
      workspaces:
        - name: source
          workspace: repository
          subPath: src

    - name: build-index
      runAfter:
        - generate-index
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: &bundleIndexImage "$(params.registry_url)/$(context.pipelineRun.namespace)/$(tasks.operator-validation.results.package_name)-index:$(tasks.operator-validation.results.bundle_version)"
        - name: CONTEXT
          value: "$(params.bundle_path)"
        # - name: DOCKERFILE
        #   value: "Dockerfile.index"
        # TODO TLS verification disabled for demo purposes
        - &buildahNoTlsVerify
          name: TLSVERIFY
          value: "false"
      workspaces:
        - name: source
          workspace: repository
          subPath: src

    # merge PR
    - name: merge-pr
      runAfter:
        - build-index
      taskRef:
        name: merge-pr
      params:
        - name: git_pr_url
          value: $(params.git_pr_url)
      workspaces:
        - name: source
          workspace: repository
          subPath: src

  # Finally- clean up
  finally:
    - name: cleanup
      taskRef:
        name: cleanup
