---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-ci-results
spec:
  params:
    - name: preflight_results_exists
    - name: md5sum
    - name: pyxis_url
    - name: cert_project_id
    - name: bundle_version
    - name: operator_name
    # results from get-ci-results-attempt.
    # They are kept if they have value, or
    # they are replaced.
    - name: test_result_id
    - name: test_logs_id
  results:
    - name: test_result_id
    - name: test_logs_id
  workspaces:
    - name: results
  steps:
    - name: check-if-results-exists
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        PREFLIGHT_RESULTS_EXISTS="$(params.preflight_results_exists)"

        if [ $PREFLIGHT_RESULTS_EXISTS == "true" ]; then
          echo "Preflight results already exists- skipping"

          echo $(params.test_result_id) | tee $(results.test_result_id.path)
          echo $(params.test_logs_id) | tee $(results.test_logs_id.path)

          exit 0
        fi
    - name: get-results
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      workingDir: $(workspaces.results.path)
      script: |
        #! /usr/bin/env bash

        # Send request to Pyxis to get the logs and test results.
        # If they exists, store them in the workspace

        echo "Downloading the artifacts"

        download-artifacts \
          --pyxis-url "$(params.pyxis_url)" \
          --pyxis-url https://pyxis.stage.engineering.redhat.com
          --cert-project-id "$(params.cert_project_id)" \
          --certification-hash "$(params.md5sum)" \
          --operator-package-version "$(params.bundle_version)" \
          --operator-name "$(params.operator_name)" \
          --cert-path /cert/tls.crt \
          --key-path /cert/tls.key \
          --verbose

        cat test_result_id | tee $(results.test_result_id.path)
        cat test_logs_id | tee $(results.test_logs_id.path)

      volumeMounts:
        - mountPath: /cert
          name: cert
  volumes:
    - name: cert
      secret:
        secretName: pyxis-auth-cert
