---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-bundle-related-data
spec:
  params:
    - name: cert_project_id
  results:
    - name: vendor_label
    - name: repository_name
    - name: isv_pid
  steps:
    - name: get-bundle-related-data
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        echo "Retrieving the data related to bundle"

        echo -n "vendor_label" | tee $(results.vendor_label.path)
        echo -n "repository_name" | tee $(results.repository_name.path)
        echo -n "isv_pid" | tee $(results.isv_pid.path)
