---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-project-related-data
spec:
  params:
    - name: cert_project_id
      description: ID of the bundle Certification Project (as in bundle ci.yaml)
  results:
    - name: vendor_label
    - name: repository_name
    - name: isv_pid
    - name: dist_method
    - name: registry
  steps:
    - name: get-project-related-data
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        echo "Retrieving the data related to bundle"

        echo -n "vendor_label" | tee $(results.vendor_label.path)
        echo -n "repository_name" | tee $(results.repository_name.path)
        echo -n "isv_pid" | tee $(results.isv_pid.path)
        echo -n "dist_method" | tee $(results.dist_method.path)
        echo -n "registry" | tee $(results.registry.path)
