---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: merge-pr
spec:
  params:
    - name: git_pr_url
  workspaces:
    - name: github-bot-token
  steps:
    - name: merge-pr
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        set -xe

        GITHUB_BOT_TOKEN_PATH=$(workspaces.github-bot-token.path)/github_bot_token.txt
        export GITHUB_BOT_TOKEN=$(cat $GITHUB_BOT_TOKEN_PATH)

        # get the PR number and the repository name from the original PR url-
        # it will be used for the api.github url
        PR_NUMBER=$(basename "$(params.git_pr_url)")
        REPO_NAME=$(echo "$(params.git_pr_url)" | sed -e "s|^https://github.com/||" -e "s|/pull/.*$||")

        API_URL=https://api.github.com/repos/${REPO_NAME}/pulls/${PR_NUMBER}/merge
        echo $API_URL

        # curl to GitHub API
        curl -X PUT \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: bearer ${GITHUB_BOT_TOKEN}" \
          $API_URL

