---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: publish-resources
spec:
  params:
    - name: cert_project_id
  steps:
    - name: publish-resources
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        echo "Publishing the Vendor and Repository"

        echo "ok"
