---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: publish-bundle
spec:
  params:
    - name: cert_project_id
    - name: container_digest
    - name: bundle_versions
  steps:
    - name: publish-bundle
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        echo "Starting bundle publish process"
        echo "Calling the IIB"
        echo "Got result- updating GitHub status"

        echo "ok"
