---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-container-image
spec:
  params:
    - name: cert_project_id
      description: ID of the bundle Certification Project (as in bundle ci.yaml)
    - name: registry
      description: certification project registry
    - name: vendor_label
      description: name of the vendor
    - name: repository_name
    - name: container_digest
      description: imagestream container_digest
    - name: bundle_version
      description: operator bundle version
    - name: is_latest
      description: boolean- should this operator version be tagged as latest?
  steps:
    - name: update-container-image
      image: registry.access.redhat.com/ubi8-minimal
      script: |
        #! /usr/bin/env bash
        echo "Updating container image"

        echo "ok"
